# Generated by Django 4.2.6 on 2023-10-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='productos',
            new_name='productos_id',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='almacen',
            new_name='almacen_id',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='proveedor_id',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='cantidad',
            new_name='cantidad_id',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
